name: cs231n
channels:
- conda-forge
dependencies:
- black
- black-jupyter
- cython
- imageio
- isort
- jupyterlab
- matplotlib
- pandas
- python
- pytorch
- ruff
- scikit-learn
- scipy
- tensorboard
- torchvision

